version: "3.7"
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php_my_admin
    ports:
      - 5000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
   
  api:
    build: 
      './md-api/'
    ports:
      - "8080:8080"
    container_name: node_container
    restart: always
    working_dir: ${WORKING_DIR}
    volumes:
      - ./md-api:${WORKING_DIR}
    command: sh -c "npm run dev"
    depends_on: 
      - db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      FROM_EMAIL: ${FROM_EMAIL}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
  react:
    image: node:10-slim
    container_name: react_container
    ports:
      - '4000:3000'
    command: sh -c "npm"
    command: sh -c "npm start"
    working_dir: ${WORKING_DIR}
    volumes:
      - ./md-web:${WORKING_DIR}
    environment:
      API_ADDRESS: ${API_ADDRESS}
      MYSQL_USER: ${MYSQL_USER}
    depends_on:
      - db
      - api

